replicaCount: 1

image:
  repository: githooks-worker
  tag: "latest"
  pullPolicy: IfNotPresent

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

webhook:
  githubSecret: ""

extraEnv: []

extraConfigMapName: ""
extraSecretName: ""

configYaml: |-
  watermill:
    driver: gochannel
