{{- if and .Values.config.createSecret (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "githook.configResourceName" . }}
  labels:
    {{- include "githook.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.key }}: |
{{ required "config.data is required when config.createSecret=true and config.existingSecret is empty" .Values.config.data | indent 4 }}
{{- end }}
