apiVersion: v1
kind: Secret
metadata:
  name: {{ include "githooks.fullname" . }}-secrets
  labels:
    {{- include "githooks.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.configYaml | b64enc | quote }}
  {{- if .Values.webhook.githubSecret }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.webhook.githubSecret | b64enc | quote }}
  {{- end }}
